### ISSUE TITLE
Play Sonos mp3 when arming alarm

### ISSUE THREAD

**Issue by ScottEgan** [ScottEgan/HomeAssistantConfig#31]
Need to download and transfer some mp3 files to home assistant to use

**Comment by ScottEgan** [comment]
Set up a generic script to use in other places
```yaml
alias: Play Sonos mp3
sequence:
  - service: sonos.snapshot
    data_template:
      entity_id: media_player.kitchen_sonos
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.kitchen_sonos
      volume_level: '{{ volume }}'
  - service: media_player.play_media
    data_template:
      entity_id: media_player.kitchen_sonos
      media_content_id: '{{ media_source }}'
      media_content_type: music
  - delay: '00:00:03'
  - service: sonos.restore
    data_template:
      entity_id: media_player.kitchen_sonos
mode: single
```
Use a script service call to pass data to the script
```yaml
service: script.play_sonos_mp3
data:
  volume: 0.5
  media_source: http://192.168.1.95:8123/local/audio/up-chime-1.mp3
