### ISSUE TITLE
Fix Garage door notifications

### ISSUE THREAD

**Issue by ScottEgan** [ScottEgan/HomeAssistantConfig#80]
Only notify if unavailable for more than 4 minutes

**Comment by ScottEgan** [comment]
Try this:

```yaml
- alias: "Notify when garage door state changes"
  description: ""
  mode: single
  trigger:

    - platform: state
      entity_id: cover.garage_door

  condition: 
    condition: template
    value_template: {{ trigger.to_state.state in ['closed', 'open', 'opening', 'closing']    # ignore unavailable state

  action:
    
    - service: notify.all_ios_devices
      data:
        title: "Garage Notification"
        message: Garage door is {{ trigger.to_state.state }} {{ as_timestamp(now()) | timestamp_custom('%-I:%M %p %b-%-d ') }}
        data:
          push:
            thread-id: Updates
```

And then add another automation to notify if state is unavailable. Maybe best to use the MyQ gateway state for that
